const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    convertMedia: (data) => ipcRenderer.send('convert-media', data),
    openFileDialog: (filters) => ipcRenderer.invoke('open-file-dialog', filters),
    saveFileDialog: (extension) => ipcRenderer.invoke('save-file-dialog', extension),
    processImageSharp: (data) => ipcRenderer.invoke('process-image-sharp', data),
    convertDocument: (data) => ipcRenderer.invoke('convert-document', data),
    convertExcelToPdf: (data) => ipcRenderer.invoke('convert-excel-to-pdf', data),
    convertPdfToWord: (data) => ipcRenderer.invoke('convert-pdf-to-word', data),
    convertImagesToWord: (data) => ipcRenderer.invoke('convert-images-to-word', data),
    mergePdfs: (data) => ipcRenderer.invoke('merge-pdfs', data),
    splitPdf: (data) => ipcRenderer.invoke('split-pdf', data),
    readFileBuffer: (path) => ipcRenderer.invoke('read-file-buffer', path),
    logToTerminal: (msg) => ipcRenderer.send('log-to-terminal', msg),
    readWord: (path) => ipcRenderer.invoke('read-word', path),
    saveToWord: (data) => ipcRenderer.invoke('save-to-word', data),
    preparePlayableMedia: (filePath) => ipcRenderer.invoke('prepare-playable-media', filePath),
    lookupDictionary: (data) => ipcRenderer.invoke('lookup-dictionary', data),
    translateOffline: (data) => ipcRenderer.invoke('translate-text-offline', data),
    synthesizeSpeech: (data) => ipcRenderer.invoke('synthesize-speech', data),
    getLearnedStats: () => ipcRenderer.invoke('get-learned-stats'),
    exportLearnedWords: (data) => ipcRenderer.invoke('export-learned-words', data),
    showItemInFolder: (path) => ipcRenderer.invoke('show-item-in-folder', path),
    openPath: (path) => ipcRenderer.invoke('open-path', path),
    getMediaMetadata: (path) => ipcRenderer.invoke('get-media-metadata', path),
    windowMinimize: () => ipcRenderer.send('window-minimize'),
    windowMaximize: () => ipcRenderer.send('window-maximize'),
    windowClose: () => ipcRenderer.send('window-close'),

    // Listeners
    onWindowMaximizedChanged: (callback) => ipcRenderer.on('window-maximized-changed', (event, value) => callback(value)),
    onConversionProgress: (callback) => ipcRenderer.on('conversion-progress', (event, value) => callback(value)),
    onDocConversionProgress: (callback) => ipcRenderer.on('doc-conversion-progress', (event, value) => callback(value)),
    onConversionDone: (callback) => ipcRenderer.on('conversion-done', (event, path) => callback(path)),
    onConversionError: (callback) => ipcRenderer.on('conversion-error', (event, err) => callback(err)),
    // New feature: Social Media Downloader
    analyzeUrl: (url) => ipcRenderer.send('analyze-url', url),
    onUrlAnalyzed: (callback) => ipcRenderer.on('url-analyzed', (event, data) => callback(data)),
    onUrlAnalyzeError: (callback) => ipcRenderer.on('url-analyze-error', (event, err) => callback(err)),
    downloadSocialMedia: (data) => ipcRenderer.send('download-social-media', data),
    onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (event, value) => callback(value)),
    onDownloadDone: (callback) => ipcRenderer.on('download-done', (event, path) => callback(path)),
    onDownloadError: (callback) => ipcRenderer.on('download-error', (event, err) => callback(err)),

    // New feature: Media Studio (Photo/Photoshop, Video/Audio Editor & Gemini AI)
    saveEditedImage: (data) => ipcRenderer.invoke('save-edited-image', data),
    geminiAiRetouch: (data) => ipcRenderer.invoke('gemini-ai-retouch', data),
    extractVideoThumbnail: (data) => ipcRenderer.invoke('extract-video-thumbnail', data),
    editVideoAdvanced: (data) => ipcRenderer.send('edit-video-advanced', data),
    onVideoEditProgress: (callback) => ipcRenderer.on('video-edit-progress', (event, value) => callback(value)),
    onVideoEditDone: (callback) => ipcRenderer.on('video-edit-done', (event, path) => callback(path)),
    onVideoEditError: (callback) => ipcRenderer.on('video-edit-error', (event, err) => callback(err)),
    editAudioAdvanced: (data) => ipcRenderer.send('edit-audio-advanced', data),
    onAudioEditProgress: (callback) => ipcRenderer.on('audio-edit-progress', (event, value) => callback(value)),
    onAudioEditDone: (callback) => ipcRenderer.on('audio-edit-done', (event, path) => callback(path)),
    onAudioEditError: (callback) => ipcRenderer.on('audio-edit-error', (event, err) => callback(err)),
    extractAudioFromVideo: (data) => ipcRenderer.invoke('extract-audio-from-video', data),
    testGeminiConnection: (apiKey) => ipcRenderer.invoke('test-gemini-connection', apiKey)
});
